package vista;

import conexion.Conexion;
import basedatos.TablaCliente;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author ediso
 */
public class VistaGestionarCliente extends javax.swing.JInternalFrame {

    private int idCliente;

    public VistaGestionarCliente() {
        initComponents();
        this.setSize(new Dimension(1200, 500));
        this.setTitle("Gestionar Clientes");
        //Cargar tabla
        this.CargarTablaClientes();

        //insertar imagen en nuestro JLabel
        ImageIcon wallpaper = new ImageIcon("D:\\Archivos\\Descargas\\SistemaDeventas1\\src\\img\\Images\\FondoGestionVentas.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(1200, 500, WIDTH));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_clientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaTelefono = new javax.swing.JTextField();
        cajaApellidoPaterno = new javax.swing.JTextField();
        cajaCalle = new javax.swing.JTextField();
        cajaCurp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaApellidoMaterno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaTipoTarjeta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cajaNumeroTarjeta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cajaNumcasa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cajaColonia = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Administrar Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane1.setViewportView(jTable_clientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1040, 270));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(51, 204, 0));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton_eliminar.setBackground(new java.awt.Color(255, 51, 51));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, 130, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 90, -1));

        cajaNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNombreKeyTyped(evt);
            }
        });
        jPanel3.add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Numero Casa:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Apellido Materno:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Calle: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Curp:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 90, -1));

        cajaTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelefonoActionPerformed(evt);
            }
        });
        cajaTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaTelefonoKeyTyped(evt);
            }
        });
        jPanel3.add(cajaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 190, 30));

        cajaApellidoPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaApellidoPaternoKeyTyped(evt);
            }
        });
        jPanel3.add(cajaApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));

        cajaCalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCalleKeyTyped(evt);
            }
        });
        jPanel3.add(cajaCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, 190, 30));

        cajaCurp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel3.add(cajaCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Apellido Paterno:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, -1));

        cajaApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaApellidoMaternoKeyTyped(evt);
            }
        });
        jPanel3.add(cajaApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Teléfono:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 90, 20));

        cajaTipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Tipo de Tarjeta", "Tarjeta de Debito", "Tarjeta de Credito", " " }));
        jPanel3.add(cajaTipoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Tipo Tarjeta:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, -1));

        cajaNumeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNumeroTarjetaKeyTyped(evt);
            }
        });
        jPanel3.add(cajaNumeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 190, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Numero Tarjeta:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 130, -1));

        cajaNumcasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNumcasaActionPerformed(evt);
            }
        });
        cajaNumcasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNumcasaKeyTyped(evt);
            }
        });
        jPanel3.add(cajaNumcasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 140, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Colonia:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 70, -1));

        cajaColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaColoniaKeyTyped(evt);
            }
        });
        jPanel3.add(cajaColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 190, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 1040, 130));

        jLabel_wallpaper.setBackground(new java.awt.Color(255, 255, 204));
        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaDeventas1/src/img/Images/FondoGestionVentas.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed

        if (cajaNombre.getText().isEmpty() && cajaApellidoPaterno.getText().isEmpty()
                && cajaCurp.getText().isEmpty() && cajaTelefono.getText().isEmpty() && cajaCalle.getText().isEmpty() && cajaApellidoMaterno.getText().isEmpty()
                && cajaColonia.getText().isEmpty())    {
            JOptionPane.showMessageDialog(null, "¡Completa todos los campos!");
        } else {

            Cliente cliente = new Cliente();
            TablaCliente controlCliente = new TablaCliente();

            cliente.setNombre(cajaNombre.getText().trim());
            cliente.setApellidoPaterno(cajaApellidoPaterno.getText().trim());
            cliente.setApellidoMaterno(cajaApellidoMaterno.getText().trim());
            cliente.setCurp(cajaCurp.getText().trim());
            cliente.setTelefono(cajaTelefono.getText().trim());
            cliente.setTipotarjeta((String) cajaTipoTarjeta.getSelectedItem());
            cliente.setNumtarjeta(cajaNumeroTarjeta.getText().trim());
            cliente.setNumCasa(Integer.parseInt(cajaNumcasa.getText().trim()));
            cliente.setCalle(cajaCalle.getText().trim());
            cliente.setColonia(cajaColonia.getText().trim());

            if (controlCliente.actualizar(cliente, idCliente)) {
                JOptionPane.showMessageDialog(null, "¡Datos del cliente actualizados!");
                this.CargarTablaClientes();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al actualizar!");
            }

        }

    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed

        TablaCliente controlCliente = new TablaCliente();
        if (idCliente == 0) {
            JOptionPane.showMessageDialog(null, "¡Seleccione un cliente!");
        } else {
            if (!controlCliente.eliminar(idCliente)) {
                JOptionPane.showMessageDialog(null, "¡Cliente Eliminado!");
                this.CargarTablaClientes();
                this.Limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡Error al eliminar cliente!");
                this.Limpiar();
            }
        }

    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void cajaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTelefonoActionPerformed

    private void cajaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaNombreKeyTyped

    private void cajaApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaApellidoPaternoKeyTyped
       char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaApellidoPaternoKeyTyped

    private void cajaApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaApellidoMaternoKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaApellidoMaternoKeyTyped

    private void cajaTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaTelefonoKeyTyped
       char[] letra = cajaTelefono.getText().toCharArray();
            if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
            if (letra.length > 9) {
                evt.consume();
            }
    }//GEN-LAST:event_cajaTelefonoKeyTyped

    private void cajaNumeroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNumeroTarjetaKeyTyped
        char[] letra = cajaNumeroTarjeta.getText().toCharArray();
            if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
            if (letra.length > 15) {
                evt.consume();
            }
    }//GEN-LAST:event_cajaNumeroTarjetaKeyTyped

    private void cajaNumcasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNumcasaKeyTyped
        char[] letra = cajaNumcasa.getText().toCharArray();
            if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
            if (letra.length > 2) {
                evt.consume();
                cajaCalle.requestFocus(); 
            }
    }//GEN-LAST:event_cajaNumcasaKeyTyped

    private void cajaCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCalleKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaCalleKeyTyped

    private void cajaColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaColoniaKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaColoniaKeyTyped

    private void cajaNumcasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNumcasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNumcasaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajaApellidoMaterno;
    private javax.swing.JTextField cajaApellidoPaterno;
    private javax.swing.JTextField cajaCalle;
    private javax.swing.JTextField cajaColonia;
    private javax.swing.JTextField cajaCurp;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaNumcasa;
    private javax.swing.JTextField cajaNumeroTarjeta;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JComboBox<String> cajaTipoTarjeta;
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_clientes;
    // End of variables declaration//GEN-END:variables

    /*
     * *****************************************************
     * metodo para limpiar
     * *****************************************************
     */
    private void Limpiar() {
        cajaNombre.setText("");
        cajaTelefono.setText("");
        cajaApellidoPaterno.setText("");
        cajaApellidoMaterno.setText("");
        cajaTipoTarjeta.setSelectedIndex(0);
        cajaNumeroTarjeta.setText("");
        cajaNumcasa.setText("");
        cajaCalle.setText("");
        cajaColonia.setText("");
        cajaCurp.setText("");
    }


    /*
     * *****************************************************
     * metodo para mostrar todos los clientes registrados
     * *****************************************************
     */
    private void CargarTablaClientes() {
        Connection con = Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql = "select * from tb_cliente";
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            VistaGestionarCliente.jTable_clientes = new JTable(model);
            VistaGestionarCliente.jScrollPane1.setViewportView(VistaGestionarCliente.jTable_clientes);

            model.addColumn("N°");//ID
            model.addColumn("nombre");
            model.addColumn("apellidoPaterno");
            model.addColumn("apelllidoMaterno");
            model.addColumn("curp");
            model.addColumn("telefono");
            model.addColumn("tipoTarjeta");
            model.addColumn("numtarjeta");
            model.addColumn("numCasa");
            model.addColumn("calle");
            model.addColumn("colonia");

            while (rs.next()) {
                Object fila[] = new Object[11];
                for (int i = 0; i < 11; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al llenar la tabla clientes: " + e);
        }
        //evento para obtener campo al cual el usuario da click
        //y obtener la interfaz que mostrara la informacion general
        jTable_clientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_point = jTable_clientes.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if (fila_point > -1) {
                    idCliente = (int) model.getValueAt(fila_point, columna_point);
                    EnviarDatosClienteSeleccionado(idCliente);//metodo
                }
            }
        });
    }


    /*
     * **************************************************
     * Metodo que envia datos seleccionados
     * **************************************************
     */
    private void EnviarDatosClienteSeleccionado(int idCliente) {
        try {
            Connection con = Conexion.conectar();
            PreparedStatement pst = con.prepareStatement(
                    "select * from tb_cliente where idCliente = '" + idCliente + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                cajaNombre.setText(rs.getString("nombre"));
                cajaApellidoPaterno.setText(rs.getString("apellidoPaterno"));
                cajaApellidoMaterno.setText(rs.getString("apellidoMaterno"));
                cajaCurp.setText(rs.getString("curp"));
                cajaTelefono.setText(rs.getString("telefono"));
                cajaTipoTarjeta.setSelectedItem(rs.getString("tipotarjeta"));
                cajaNumeroTarjeta.setText(rs.getString("numTarjeta"));
                cajaNumcasa.setText(rs.getString("numCasa"));
                cajaCalle.setText(rs.getString("calle"));
                cajaColonia.setText(rs.getString("colonia"));
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al seleccionar cliente: " + e);
        }
    }

}
