package vista;

import basedatos.TablaCategoria;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Categoria;
import static vista.VistaCapturaProducto.getUpper;

public class VistaCapturaCategoria extends javax.swing.JInternalFrame {

    public VistaCapturaCategoria() {
        initComponents();
        this.setSize(new Dimension(400, 200));
        this.setTitle("Nueva Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cajaDescrpcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nueva Categoria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Defina la Categoria: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        cajaDescrpcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaDescrpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDescrpcionActionPerformed(evt);
            }
        });
        cajaDescrpcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaDescrpcionKeyTyped(evt);
            }
        });
        getContentPane().add(cajaDescrpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 170, -1));

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 90, 30));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaDeventas1/src/img/Images/Fondo1.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Categoria categoria = new Categoria();
        TablaCategoria controlCategoria = new TablaCategoria();

        //validamos camoos vacios
        if (cajaDescrpcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete  todos los campos");
        } else {
            if (!controlCategoria.existeCategoria(cajaDescrpcion.getText().trim())) {
                categoria.setDescripcion(cajaDescrpcion.getText().trim());
                if (controlCategoria.guardar(categoria)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "La Categoria ya esta registrada en la Base de Datos");
            }
        }
        //limpiar campo
        cajaDescrpcion.setText("");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cajaDescrpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDescrpcionActionPerformed
        String descripcion = cajaDescrpcion.getText();
        if (descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el nombre de la categoria");
        } else {
            cajaDescrpcion.setText(getUpper(descripcion));
            btnGuardar.setBackground(new Color(255, 0, 255));
            btnGuardar.requestFocus();
        }
    }//GEN-LAST:event_cajaDescrpcionActionPerformed

    private void cajaDescrpcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaDescrpcionKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaDescrpcionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField cajaDescrpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
}
