package vista;

import basedatos.TablaUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Ernesto y Emmanuel
 */
public class vistaCapturaUsuario extends javax.swing.JInternalFrame {
    
    public vistaCapturaUsuario() {
        initComponents();
        this.setSize(new Dimension(400, 370));
        this.setTitle("Nuevo Usuario");
        
        cajaPassword.setVisible(true);
        txt_password_visible.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaApellidoPaterno = new javax.swing.JTextField();
        cajaUsuario = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cajaTelefono = new javax.swing.JTextField();
        cajaPassword = new javax.swing.JPasswordField();
        jCheckBox_ver_clave = new javax.swing.JCheckBox();
        txt_password_visible = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaApellidoMaterno = new javax.swing.JTextField();
        jLabel_wallpaper = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido Paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Usuario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, -1));

        cajaNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });
        cajaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNombreKeyTyped(evt);
            }
        });
        getContentPane().add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, -1));

        cajaApellidoPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaApellidoPaternoActionPerformed(evt);
            }
        });
        cajaApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaApellidoPaternoKeyTyped(evt);
            }
        });
        getContentPane().add(cajaApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 170, -1));

        cajaUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, 30));

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 90, 40));

        cajaTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelefonoActionPerformed(evt);
            }
        });
        cajaTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(cajaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 170, 30));

        cajaPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cajaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(cajaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 170, 30));

        jCheckBox_ver_clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox_ver_claveMouseClicked(evt);
            }
        });
        getContentPane().add(jCheckBox_ver_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 20));

        txt_password_visible.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txt_password_visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 170, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Apellido Materno:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, -1));

        cajaApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaApellidoMaternoActionPerformed(evt);
            }
        });
        cajaApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaApellidoMaternoKeyTyped(evt);
            }
        });
        getContentPane().add(cajaApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        jLabel_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaDeventas1/src/img/Images/Fondo1.png"))); // NOI18N
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (cajaNombre.getText().isEmpty() || cajaApellidoPaterno.getText().isEmpty() || cajaUsuario.getText().isEmpty()
                || cajaPassword.getText().isEmpty() || cajaTelefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
        } else {
            //validamos si el usuaro ya esta registrado
            Usuario usuario = new Usuario();
            TablaUsuario controlUsuario = new TablaUsuario();
            if (!controlUsuario.existeUsuario(cajaUsuario.getText().trim())) {
                //enviamos datos del usuario
                usuario.setNombre(cajaNombre.getText().trim());
                usuario.setApellidoPaterno(cajaApellidoPaterno.getText().trim());
                usuario.setApellidoMaterno(cajaApellidoMaterno.getText().trim());
                usuario.setUsuario(cajaUsuario.getText().trim());
                usuario.setPassword(cajaPassword.getText().trim());
                usuario.setTelefono(cajaTelefono.getText().trim());
                
                if (controlUsuario.guardar(usuario)) {
                    JOptionPane.showMessageDialog(null, "¡Usuario Registrado!");
                } else {
                    JOptionPane.showMessageDialog(null, "¡Error al registrar Usuario!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El Usuario ya esta registrado, ingrese otro.");
            }
        }
        this.Limpiar();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jCheckBox_ver_claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox_ver_claveMouseClicked
        if (jCheckBox_ver_clave.isSelected() == true) {
            String pass = "";
            char[] passIngresado = cajaPassword.getPassword();
            for (int i = 0; i < passIngresado.length; i++) {
                pass += passIngresado[i];
            }
            txt_password_visible.setText(pass);
            cajaPassword.setVisible(false);
            txt_password_visible.setVisible(true);
        } else {
            String passwordIngresado = txt_password_visible.getText().trim();
            cajaPassword.setText(passwordIngresado);
            cajaPassword.setVisible(true);
            txt_password_visible.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox_ver_claveMouseClicked

    private void cajaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cajaNombreKeyTyped

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
        String cod = cajaNombre.getText();
        if (cod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el nombre del usuario");
        } else {
            cajaNombre.setText(getUpper(cod));
            cajaApellidoPaterno.requestFocus();
        }
           
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaApellidoPaternoActionPerformed
        String cod = cajaApellidoPaterno.getText();
        if (cod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el apellido paterno del usuario");
        } else {
            cajaApellidoPaterno.setText(getUpper(cod));
            cajaApellidoMaterno.requestFocus();
        }
    }//GEN-LAST:event_cajaApellidoPaternoActionPerformed

    private void cajaApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaApellidoMaternoActionPerformed
        String cod = cajaApellidoMaterno.getText();
        if (cod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el apellido materno del usuario");
        } else {
            cajaApellidoMaterno.setText(getUpper(cod));
            cajaUsuario.requestFocus();
        }
    }//GEN-LAST:event_cajaApellidoMaternoActionPerformed

    private void cajaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUsuarioActionPerformed
        String cod = cajaUsuario.getText();
        if (cod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el usuario del usuario");
        } else {
            cajaPassword.requestFocus();
        }
    }//GEN-LAST:event_cajaUsuarioActionPerformed

    private void cajaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaPasswordActionPerformed
        String cod = cajaPassword.getText();
        if (cod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el password del usuario");
        } else {
            cajaTelefono.requestFocus();
        }
    }//GEN-LAST:event_cajaPasswordActionPerformed

    private void cajaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelefonoActionPerformed
        String cod = cajaTelefono.getText();
        if (cod.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el telefono del usuario");
        } else {
            btnGuardar.setBackground(new Color(255, 0, 255));
            btnGuardar.requestFocus();
        }
    }//GEN-LAST:event_cajaTelefonoActionPerformed

    private void cajaApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaApellidoPaternoKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cajaApellidoPaternoKeyTyped

    private void cajaApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaApellidoMaternoKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cajaApellidoMaternoKeyTyped

    private void cajaTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaTelefonoKeyTyped
        char[] letra = cajaTelefono.getText().toCharArray();
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        if (letra.length > 9) {
            evt.consume();
            btnGuardar.setBackground(new Color(255, 0, 255));
            btnGuardar.requestFocus();
        }
    }//GEN-LAST:event_cajaTelefonoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField cajaApellidoMaterno;
    private javax.swing.JTextField cajaApellidoPaterno;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JPasswordField cajaPassword;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JCheckBox jCheckBox_ver_clave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JTextField txt_password_visible;
    // End of variables declaration//GEN-END:variables
     /**
     *
     * Metodo para limpiar campos
     */
    private void Limpiar() {
        cajaNombre.setText("");
        cajaApellidoPaterno.setText("");
        cajaApellidoMaterno.setText("");
        cajaPassword.setText("");
        cajaUsuario.setText("");
        cajaTelefono.setText("");
    }
    
    public static String getUpper(String mgg) {
        String[] substring = mgg.split(" ");
        int i = 0;
        for(String item : substring) {
            if(item.length()>2) {
                StringBuilder sb = new StringBuilder(item.trim().toLowerCase());
                sb.setCharAt(0, Character.toUpperCase(item.charAt(0)));
                substring[i] = sb.toString();
            }
            i++;
        }
        String cadenafinal = String.join(" ", substring);
        return cadenafinal;
    }
    
}
