package vista;

import basedatos.TablaCliente;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Cliente;
import static vista.VistaCapturaProvedores.getUpper;

/**
 *
 * @author ediso
 */
public class VistaCapturaCliente extends javax.swing.JInternalFrame {

    public VistaCapturaCliente() {
        initComponents();
        this.setSize(new Dimension(687, 300));
        this.setTitle("Nuevo Cliente");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaApellidoPaterno = new javax.swing.JTextField();
        cajaCurp = new javax.swing.JTextField();
        cajaTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cajaCalle = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaApellidoMaterno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cajaTipotarjeta = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cajaNumTarjeta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cajaNumCasa = new javax.swing.JTextField();
        cajaColonia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nuevo Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido Materno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Colonia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Calle:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 90, -1));

        cajaNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNombreActionPerformed(evt);
            }
        });
        cajaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNombreKeyTyped(evt);
            }
        });
        getContentPane().add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        cajaApellidoPaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaApellidoPaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaApellidoPaternoActionPerformed(evt);
            }
        });
        cajaApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaApellidoPaternoKeyTyped(evt);
            }
        });
        getContentPane().add(cajaApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, -1));

        cajaCurp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaCurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCurpActionPerformed(evt);
            }
        });
        cajaCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCurpKeyTyped(evt);
            }
        });
        getContentPane().add(cajaCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, -1));

        cajaTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTelefonoActionPerformed(evt);
            }
        });
        cajaTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(cajaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));

        btnGuardar.setBackground(new java.awt.Color(102, 255, 51));
        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 90, 30));

        cajaCalle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCalleActionPerformed(evt);
            }
        });
        cajaCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaCalleKeyTyped(evt);
            }
        });
        getContentPane().add(cajaCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Apellido Paterno:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, -1));

        cajaApellidoMaterno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaApellidoMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaApellidoMaternoActionPerformed(evt);
            }
        });
        cajaApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaApellidoMaternoKeyTyped(evt);
            }
        });
        getContentPane().add(cajaApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 170, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Curp:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 20));

        cajaTipotarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Tipo de Tarjeta", "Tarjeta de Debito", "Tarjeta de Credito", " " }));
        cajaTipotarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cajaTipotarjetaItemStateChanged(evt);
            }
        });
        cajaTipotarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTipotarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(cajaTipotarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tipo de Tarjeta:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 120, 20));

        cajaNumTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNumTarjetaActionPerformed(evt);
            }
        });
        cajaNumTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNumTarjetaKeyTyped(evt);
            }
        });
        getContentPane().add(cajaNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Numero de Tarjeta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 20));

        cajaNumCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNumCasaActionPerformed(evt);
            }
        });
        cajaNumCasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaNumCasaKeyTyped(evt);
            }
        });
        getContentPane().add(cajaNumCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 150, -1));

        cajaColonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaColoniaActionPerformed(evt);
            }
        });
        cajaColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaColoniaKeyTyped(evt);
            }
        });
        getContentPane().add(cajaColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Numero de Casa:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SistemaDeventas1/src/img/Images/Fondo1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        Cliente cliente = new Cliente();
        TablaCliente controlCliente = new TablaCliente();

        if (!cajaNombre.getText().isEmpty() && !cajaApellidoPaterno.getText().isEmpty() && !cajaCurp.getText().isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Correcto");

            if (!controlCliente.existeCliente(cajaCurp.getText().trim())) {

                cliente.setNombre(cajaNombre.getText().trim());
                cliente.setApellidoPaterno(cajaApellidoPaterno.getText().trim());
                cliente.setApellidoMaterno(cajaApellidoMaterno.getText().trim());
                cliente.setCurp(cajaCurp.getText().trim());
                cliente.setTelefono(cajaTelefono.getText().trim());
                cliente.setTipotarjeta((String) cajaTipotarjeta.getSelectedItem());
                cliente.setNumtarjeta(cajaNumTarjeta.getText().trim());
                cliente.setNumCasa(Integer.parseInt(cajaNumCasa.getText().trim()));
                cliente.setCalle(cajaCalle.getText().trim());
                cliente.setColonia(cajaColonia.getText().trim());
                

                if (controlCliente.guardar(cliente)) {
                    JOptionPane.showMessageDialog(null, "Registro Guardado");
                    cajaNombre.setBackground(Color.green);
                    cajaApellidoPaterno.setBackground(Color.green);
                    cajaApellidoMaterno.setBackground(Color.green);
                    cajaCurp.setBackground(Color.green);
                    cajaTelefono.setBackground(Color.green);
                    cajaTipotarjeta.setBackground(Color.green);
                    cajaNumTarjeta.setBackground(Color.green);
                    cajaNumCasa.setBackground(Color.green);
                    cajaCalle.setBackground(Color.green);
                    cajaColonia.setBackground(Color.green);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al Guardar");
                }

            } else {
                JOptionPane.showMessageDialog(null, "El cliente ya esta registrado en la Base de Datos.");
                    cajaNombre.setBackground(Color.white);
                    cajaApellidoPaterno.setBackground(Color.white);
                    cajaApellidoMaterno.setBackground(Color.white);
                    cajaCurp.setBackground(Color.white);
                    cajaTelefono.setBackground(Color.white);
                    cajaTipotarjeta.setBackground(Color.white);
                    cajaNumTarjeta.setBackground(Color.white);
                    cajaNumCasa.setBackground(Color.white);
                    cajaCalle.setBackground(Color.white);
                    cajaColonia.setBackground(Color.white);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Completa todos los campos");
                    cajaNombre.setBackground(Color.red);
                    cajaApellidoPaterno.setBackground(Color.red);
                    cajaApellidoMaterno.setBackground(Color.red);
                    cajaCurp.setBackground(Color.red);
                    cajaTelefono.setBackground(Color.red);
                    cajaTipotarjeta.setBackground(Color.red);
                    cajaNumTarjeta.setBackground(Color.red);
                    cajaNumCasa.setBackground(Color.red);
                    cajaCalle.setBackground(Color.red);
                    cajaColonia.setBackground(Color.red);
        }
        //metodo limpiar
        this.Limpiar();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cajaTipotarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTipotarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTipotarjetaActionPerformed

    private void cajaCurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCurpActionPerformed
         String curp = cajaCurp.getText();
        if (curp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite la curp del cliente");
        } else {
            cajaCurp.setText(convertirLetrasAMayusculas(curp));
            cajaNombre.requestFocus();
        }
    }//GEN-LAST:event_cajaCurpActionPerformed

    private void cajaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNombreActionPerformed
         String nombre = cajaNombre.getText();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el nombre del cliente");
        } else {
            cajaNombre.setText(getUpper(nombre));
            cajaApellidoPaterno.requestFocus();
            
        }
    }//GEN-LAST:event_cajaNombreActionPerformed

    private void cajaApellidoPaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaApellidoPaternoActionPerformed
        String paterno = cajaApellidoPaterno.getText();
        if (paterno.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el apellido paterno del cliente");
        } else {
            cajaApellidoPaterno.setText(getUpper(paterno));
            cajaApellidoMaterno.requestFocus();
            
        }
    }//GEN-LAST:event_cajaApellidoPaternoActionPerformed

    private void cajaApellidoMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaApellidoMaternoActionPerformed
        String materno = cajaApellidoMaterno.getText();
        if (materno.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el apellido materno del cliente");
        } else {
            cajaApellidoMaterno.setText(getUpper(materno));
            cajaTelefono.requestFocus();
        }
    }//GEN-LAST:event_cajaApellidoMaternoActionPerformed

    private void cajaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTelefonoActionPerformed
        String telefono = cajaTelefono.getText();
        if (telefono.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el telefono del cliente");
        } else {
            cajaTelefono.setText(getUpper(telefono));
            cajaTipotarjeta.requestFocus();
        }
    }//GEN-LAST:event_cajaTelefonoActionPerformed

    private void cajaTipotarjetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cajaTipotarjetaItemStateChanged
        cajaNumTarjeta.requestFocus();
    }//GEN-LAST:event_cajaTipotarjetaItemStateChanged

    private void cajaNumTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNumTarjetaActionPerformed
        String numtar = cajaNumTarjeta.getText();
        if (numtar.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el numero de la tarjeta del cliente");
        } else {
            cajaNumTarjeta.setText(getUpper(numtar));
            cajaNumCasa.requestFocus();
        }
    }//GEN-LAST:event_cajaNumTarjetaActionPerformed

    private void cajaNumCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNumCasaActionPerformed
        String numcasa = cajaNumCasa.getText();
        if (numcasa.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite el numero de la casa del cliente");
        } else {
            cajaNumCasa.setText(getUpper(numcasa));
            cajaCalle.requestFocus();
        }
    }//GEN-LAST:event_cajaNumCasaActionPerformed

    private void cajaCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCalleActionPerformed
        String calle = cajaCalle.getText();
        if (calle.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite la calle del cliente");
        } else {
            cajaCalle.setText(getUpper(calle));
            cajaColonia.requestFocus();
        }
    }//GEN-LAST:event_cajaCalleActionPerformed

    private void cajaColoniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaColoniaActionPerformed
        String colonia = cajaColonia.getText();
        if (colonia.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite la colonia del cliente");
        } else {
            cajaColonia.setText(getUpper(colonia));
            btnGuardar.setBackground(new Color(255, 0, 255));
            btnGuardar.requestFocus();
        }
    }//GEN-LAST:event_cajaColoniaActionPerformed

    private void cajaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaNombreKeyTyped

    private void cajaApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaApellidoPaternoKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaApellidoPaternoKeyTyped

    private void cajaApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaApellidoMaternoKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaApellidoMaternoKeyTyped

    private void cajaCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCalleKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaCalleKeyTyped

    private void cajaColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaColoniaKeyTyped
        char caracter = evt.getKeyChar();
        if (!(Character.isLetter(caracter) || caracter == KeyEvent.VK_SPACE || caracter == KeyEvent.VK_BACK_SPACE)) {
            evt.consume(); 
	}
    }//GEN-LAST:event_cajaColoniaKeyTyped

    private void cajaTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaTelefonoKeyTyped
        char[] letra = cajaTelefono.getText().toCharArray();
            if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
            if (letra.length > 9) {
                evt.consume();
                cajaNumTarjeta.requestFocus();
            }else{
               
           }
    }//GEN-LAST:event_cajaTelefonoKeyTyped

    private void cajaNumTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNumTarjetaKeyTyped
        char[] letra = cajaNumTarjeta.getText().toCharArray();
            if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
            if (letra.length > 15) {
                evt.consume();
                cajaNumCasa.requestFocus();
            }
    }//GEN-LAST:event_cajaNumTarjetaKeyTyped

    private void cajaNumCasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaNumCasaKeyTyped
        char[] letra = cajaNumCasa.getText().toCharArray();
            if (!Character.isDigit(evt.getKeyChar())) {
                evt.consume();
            }
            if (letra.length > 2) {
                evt.consume();
                cajaCalle.requestFocus(); 
            }
    }//GEN-LAST:event_cajaNumCasaKeyTyped

    private void cajaCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaCurpKeyTyped
        char[] letra = cajaCurp.getText().toCharArray();
            if (letra.length > 17) {
                evt.consume();
                cajaNombre.requestFocus(); 
            }else{
               
            }
    }//GEN-LAST:event_cajaCurpKeyTyped



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField cajaApellidoMaterno;
    private javax.swing.JTextField cajaApellidoPaterno;
    private javax.swing.JTextField cajaCalle;
    private javax.swing.JTextField cajaColonia;
    private javax.swing.JTextField cajaCurp;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaNumCasa;
    private javax.swing.JTextField cajaNumTarjeta;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JComboBox<String> cajaTipotarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
     /**
     *
     * Metodo para limpiar campos
     */
    private void Limpiar() {
        cajaNombre.setText("");
        cajaApellidoPaterno.setText("");
        cajaApellidoMaterno.setText("");
        cajaCurp.setText("");
        cajaTelefono.setText("");
        cajaTipotarjeta.setSelectedIndex(0);
        cajaNumTarjeta.setText("");
        cajaNumCasa.setText("");
        cajaCalle.setText("");
        cajaColonia.setText("");
    }
    
    public static String convertirLetrasAMayusculas(String cadena) {
        if (cadena == null || cadena.isEmpty()) {
            return cadena;
        }

        StringBuilder resultado = new StringBuilder();

        for (int i = 0; i < cadena.length(); i++) {
            char c = cadena.charAt(i);
            if (Character.isLetter(c)) {
                resultado.append(Character.toUpperCase(c));
            } else {
                resultado.append(c);
            }
        }

        return resultado.toString();
    }

}
